//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Trabajo
    {
        public int idTrabajo { get; set; }

        [Required(ErrorMessage = "Ingresar titulo")]
        [DisplayName("Titulo de trabajo")]
        public string titulo { get; set; }

        [Required(ErrorMessage = "Ingresa descripcion")]
        [DisplayName("Descripcion de trabajo")]
        public string descripcion { get; set; }

        [Required(ErrorMessage = "Seleccionar categoria")]
        [DisplayName("Categoria")]
        public Nullable<int> idCategoria { get; set; }

        [Required(ErrorMessage = "Ingresa fecha inicio")]
        [DisplayName("Fecha inicial")]
        public string fechaInicial { get; set; }

        [Required(ErrorMessage = "Ingresa fecha asignada")]
        [DisplayName("Fecha Asignada")]
        public string fechaAsignada { get; set; }

        [Required(ErrorMessage = "Ingresa fecha inicio")]
        [DisplayName("Fecha Final")]
        public string fechaFinal { get; set; }

        [Required(ErrorMessage = "Seleccionar estado actual del trabajo")]
        [DisplayName("Estado actual")]
        public Nullable<int> idEstado { get; set; }

        [Required(ErrorMessage = "Seleccionar tipo de usuario")]
        [DisplayName("Tipo de usuario")]
        public Nullable<int> idUsuario { get; set; }

        [Required(ErrorMessage = "Ingresar costo de trabajo")]
        [DisplayName("Costo")]
        public Nullable<int> costoTrabajo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual EstadoTrabajo EstadoTrabajo { get; set; }
        public virtual RegistroUsuario RegistroUsuario { get; set; }
    }
}
