//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoPatronusWebEntities : DbContext
    {
        public ProyectoPatronusWebEntities()
            : base("name=ProyectoPatronusWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<EstadoTrabajo> EstadoTrabajoes { get; set; }
        public virtual DbSet<RegistroUsuario> RegistroUsuarios { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public virtual DbSet<Trabajo> Trabajoes { get; set; }
        public virtual DbSet<PAIS> PAISES { get; set; }
    }
}
