//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        public int idTrabajo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string fechaInicial { get; set; }
        public string fechaAsignada { get; set; }
        public string fechaFinal { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> costoTrabajo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual EstadoTrabajo EstadoTrabajo { get; set; }
        public virtual RegistroUsuario RegistroUsuario { get; set; }
    }
}
